### ISSUE TITLE
New feature: Run action against multiple organizations

### ISSUE THREAD

**Issue by zkoppert** [github/stale-repos#12]
It would be great to give this action the name of an enterprise or a list of organizations since many OSPOs have more than one GitHub org.

**Comment by hopkinsth** [comment]
Would recommend using [GHA's matrix strategy feature](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to accomplish this rather than specifically building support for it. This feature may already solve most of the multi-org need here.

In my use-case, I am running the stale-repos tool with GitHub App authentication, and to do so, I need to pass a separate auth token for each org. The matrix strategy works really well for that.

Maybe a sample configuration is enough here:
```yaml
on:
  - workflow_dispatch
name: Run the report
jobs: 
  report:
    name: run report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org: [org1, org2]
    steps:
      - name: "run stale-repos"
        uses: docker://ghcr.io/github/stale_repos:v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ORGANIZATION: ${{ matrix.org }}
          INACTIVE_DAYS: 365
```
