### ISSUE TITLE
Activity Method - default_branch_updated not working properly

### ISSUE THREAD

**Issue by bigswede74** [github/stale-repos#152]
### Describe the bug

When `ACTIVITY_METHOD = default_branch_updated` repos with the last commit date outside of the `INACTIVE_DAYS` are not returned as stale repos.

### To Reproduce

1. Create a repository in your organization
2. Add a workflow to check for stale repos
3. Add the state repo action as shown below
```yml      
- name: Run stale_repos tool
  uses: github/stale-repos@v1
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ORGANIZATION: ${{ github.repository_owner }}
    EXEMPT_TOPICS: "reserved"
    INACTIVE_DAYS: 60
    ACTIVITY_METHOD: "default_branch_updated"
```
5. Verify you have a stale repo by running the below GH CLI command and verifying the last commit date
```bash
gh api repos/{owner}/{repo}/commits | jq -r '.[0] | "\(.sha) \(.commit.message) \(.commit.author.name) \(.commit.author.date)"'
```
6. Run your workflow and verify the repo is not returned as a stale repo

### Expected behavior

Any repository with the last commit date outside of the `INACTIVE_DAYS` should be returned as a stale repo.

### Additional context

My repos have the visibility of `Internal` but after looking in the code for this action this does not seem to matter.
