### ISSUE TITLE
Markdown Table output is "off"

### ISSUE THREAD

**Issue by sysadmiral** [github/stale-repos#176]
### Describe the bug

The produced markdown table has the normal separators on line 2 but the output isn't quite right and so the markdown doesn't render.

This is the outputted column headers and the separators on line 2:
```
| Repository URL | Days Inactive | Last Push Date | Visibility | Days Since Last Release | Days Since Last PR |
| --- | --- | --- | ---: | ---: |
```
There are only five columns in line 2 which is less than the six column headers and there are some unecessary colons in the output.

### To Reproduce

Not sure. I've setup the workflow to pass the output to the create-issue-from-file action so I'm hoping the output isn't being altered somehow.

Here is my redacted workflow:

```yaml
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * 4' # 0530 on a thursday

name: Run the stale-repos report

permissions:
    contents: read

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Run stale_repos tool
      uses: github/stale-repos@ba84f4865211804e46c78d401815ae722ce6a498 # v1
      env:
        GH_APP_ID: ${{ secrets.APP_ID }}
        GH_APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
        GH_APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        INACTIVE_DAYS: 180
        ACTIVITY_METHOD: "pushed"
        ADDITIONAL_METRICS: "release,pr"

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@ad38cffc07bac6e3857755914c4c88bfd2db4da4 # v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Check for the stale report issue
      run: |
        ISSUE_NUMBER=$(gh search issues "Stale repository report" --match title --json number --jq ".[0].number")
        echo "issue_number=$ISSUE_NUMBER" >> "$GITHUB_ENV"
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}

    - name: Create issue
      uses: peter-evans/create-issue-from-file@24452a72d85239eacf1468b0f1982a9f3fec4c94 # v5
      with:
        issue-number: ${{ env.issue_number }}
        title: Stale repository report
        content-filepath: ./stale_repos.md
        token: ${{ steps.generate-token.outputs.token }}
```

### Expected behavior

The columns in the markdown are the same number on each row.
