### ISSUE TITLE
Pulled Docker image is stuck at stale_repos:v1

### ISSUE THREAD

**Issue by bcbrookman** [github/stale-repos#325]
### Describe the bug

Despite setting a specific version (@v2, @v3.0.0, etc.), the Docker image that's pulled is always `stale_repos:v1` which isn't updated. 

I believe this is happening because the `action.yml` metadata file still references the `v1` image, even in later releases.

https://github.com/github/stale-repos/blob/1d817944e292bc62663d58de785e85d34edd54b6/action.yml#L8-L10

### To Reproduce

For example,  when using `github/stale-repos@v2` as shown in the README examples.

```yaml
steps:
      - name: Run stale_repos tool
        uses: github/stale-repos@v2
        env:
<...>
```

The image pulled in the Actions log is `ghcr.io/github/stale_repos:v1`

```
Pull down action image 'ghcr.io/github/stale_repos:v1'
  /usr/bin/docker pull ghcr.io/github/stale_repos:v1
<...>
```

Using a docker path instead of the action name is a potential workaround.

```yaml
steps:
      - name: Run stale_repos tool
        uses: docker://ghcr.io/github/stale_repos:v2
        env:
<...>
```

### Expected behavior

I would expect the action version and the pulled docker image to correspond. In other words, I expect `@v2` to pull a Docker image containing the code released at `v2.x.x`
